### ISSUE TITLE
JATS: Plain text citation

### ISSUE THREAD

**Issue by rgieseke** [stencila/encoda#873]
Mixed citations (e.g. originally from bibitems in LaTeX) are not parsed when reading from JATS-XML.

I think the `mixed-content` should actually be `mixed-citation`: https://github.com/stencila/encoda/blob/master/src/codecs/jats/index.ts#L1165

Even nicer would probably be to have all elements of the `mixed-citation` as inline elements to keep e.g. parts in italics.

```xml
<mixed-citation>Norman de Plume <italic>The book of XML problems</italic>. XtraPress 2021.</mixed-citation>
```

Maybe this could be filed as `description` or `comment`?

https://schema.stenci.la/creativework

**Comment by nokome** [comment]
I think the ideal way to handle a `<mixed-citation>` would be to try to "decode" it (ie. parse it) into a `CreativeWork`. If we do that then in text `Cite` nodes will work as expected (ie. show authors and years if needed).

With the fix that you made the entirety of the `<mixed-citation>`

```yaml
type: Article
id: pone-0091296-Choat1
authors: []
title: >-
      Choat JH (2012) Spawning aggregations in reef fishes; ecological and
      evolutionary processes. In: Sadovy de Mitcheson Y, Colin PL, editors. Reef
      Fish Spawning Aggregations: Biology, Research and Management. Heidelberg:
      Springer. pp. 85–116.
```

whereas what we want is the bibliographic info to be parsed out of the `<mixed-citation>` into

```yaml
type: CreativeWork
authors:
  - type: Person
    familyNames:
      - Choat
    givenNames:
      - John Howard
datePublished:
  type: Date
  value: '2011-09-20'
identifiers:
  - type: PropertyValue
    name: doi
    propertyID: https://registry.identifiers.org/registry/doi
    value: 10.1007/978-94-007-1980-4_4
isPartOf:
  type: Periodical
  name: 'Reef Fish Spawning Aggregations: Biology, Research and Management'
publisher:
  type: Organization
  name: Springer Netherlands
title: Spawning Aggregations in Reef Fishes; Ecological and Evolutionary Processes
url: http://dx.doi.org/10.1007/978-94-007-1980-4_4
```

In Encoda, rather than trying to parse references into a `CreativeWork`, we take the approach suggested [here]( https://www.crossref.org/labs/resolving-citations-we-dont-need-no-stinkin-parser/) and query CrossRef for bibliographic info.  I didn't write the above YAML out by hand but rather used the `crossref` codec:

```sh
./encoda convert "Choat JH (2012) Spawning aggregations in reef fishes; evolutionary processes." --from crossref - --to yaml
```

I suggest that we use this approach for JATS `<mixed-citation>` (as we do in the `reshape` [function](https://github.com/stencila/encoda/blob/master/src/util/reshape.ts#L681)). However, I think it would be wise to perhaps put it in `name` or `alternateNames` or similar (I think `description` should be avoided because that is where the abstract goes and in some cases we actually have that; and `comment` has a different semantic structure) and then do the CrossRef querying as a separate enrichment step that won't cause a failure, if for instance there is no network connection.
