### ISSUE TITLE
JATS: Footnote support

### ISSUE THREAD

**Issue by rgieseke** [stencila/encoda#880]
Probably related to issue #144 

How would one add support to read a footnote as an inline element as part of a paragraph?
Right now it's rendered as another paragraph _next_ to the paragraph which has the annotated word as the last word.

E.g. JATS:
```xml
    <p id="p1">Text<fn id="idm6"><p id="footnote1">Footy note about Text.</p></fn> begins and ends.</p>
```
To JSON:
```json
"content": [
    {
      "type": "Paragraph",
      "id": "p1",
      "content": [
        "Text"
      ]
    },
    {
      "type": "Paragraph",
      "id": "footnote1",
      "content": [
        "Footy note about Text."
      ]
    },
    {
      "type": "Paragraph",
      "content": [
        " begins and ends."
      ]
    }
```
It should be inline like a mark i think:
```json
  {
      "type": "Paragraph",
      "id": "p2",
      "content": [
        "Normal Text, ",
        {
          "type": "Strong",
          "content": [
            "bold"
          ]
        },
        " or not."
      ]
    }

```
I played around with adding a `decodeFootnote` function but don't really know what the best approach would be.

**Comment by nokome** [comment]
Thanks for raising this @rgieseke. I propose a new `Note` type that would encompass footnotes and endnotes (and perhaps default to being an inline note i.e. in HTML it appears when you hover over it?):

```json
[
  {
    "type": "Paragraph",
    "id": "p1",
    "content": ["Text"]
  },
  {
    "type": "Note",
    "id": "idm6",
    "noteType": "Footnote",
    "content": [
      {
        "type": "Paragraph",
        "id": "footnote1",
        "content": ["Footy note about Text."]
      }
    ]
  },
  {
    "type": "Paragraph",
    "content": [" begins and ends."]
  }
]
```

The `Note.schema.yaml` in https://github.com/stencila/schema/tree/master/schema would look something like,

```yaml
title: Note
'@id': stencila:Note
extends: Entity
role: secondary
status: unstable
description: .
properties:
  noteType:
    '@id': stencila:noteType
    description: Determines where the note content is displayed within document.
    type: string
    enum:
      - Footnote
      - Endnote
  content:
    '@id': stencila:content
    description: Content of the note, usually a paragraph.
    type: array
    items:
      $ref: BlockContent
    $comment: |
      Most notes will have a single paragraph but could have multiple
      paragraphs, tables and even figures.
required:
  - content
```

But needs more research into how other document schemas represent footnotes etc e.g. JATS, Pandoc, MDAST.
